### ISSUE TITLE
ch09-02章节的示例标号与原版不一致

### ISSUE THREAD

**Issue by lcofjp** [KaiserY/trpl-zh-cn#133]
ch09-02章节的示例标号与原版不一致

这样导致了一些问题，比如：
>其功能再一次与示例 9-5 和示例 9-5 保持一致，不过这是一个与众不同且更符合工程学的写法。

**Comment by shingtaklam1324** [comment]
在TRPL原文中， 那一段是 9-8, 在中文版中少了一个例子以及解释少了一段。 原文中是 9-6 和 9-7, 中文版中应该是 9-5 和 9-6

**Comment by shingtaklam1324** [comment]
@lcofjp 已修复

**Comment by KaiserY** [comment]
第九章已更新，有问题欢迎 reopen
