### ISSUE TITLE
发现一个错误

### ISSUE THREAD

**Issue by pearzl** [KaiserY/trpl-zh-cn#157]
在15.5节，listing15-23后面的一段。

>
>   One important part of this code is that the Messenger trait has one method, send, that takes an immutable reference to self and text of the message. 
> -------
>  这些代码中一个重要部分是拥有一个方法 send 的 Messenger trait，其获取一个 self 的可变引用和文本信息。
> 

这里应该是不可变引用，是个笔误吧。

**Comment by pearzl** [comment]
https://github.com/KaiserY/trpl-zh-cn/pull/158

**Comment by xiaods** [comment]
should be closed by merged PR https://github.com/KaiserY/trpl-zh-cn/pull/158
