### ISSUE TITLE
mod-和文件系统章节中，翻译与版本实际不符

### ISSUE THREAD

**Issue by honyxiao** [KaiserY/trpl-zh-cn#177]
翻译中是这样：
Cargo 默认会创建一个库 crate 除非指定其他项目类型，所以如果不像一直以来那样加入 --bin 参数则项目将会是一个库：

但是执行cargo new --help
    --bin               Use a binary (application) template [default]
    --lib               Use a library template

指令帮助说明，bin才是默认的方式。
没看过英文版本，不知道是翻译问题，还是英文版就错误。

**Comment by hr567** [comment]
默认使用 --bin 参数是 Rust 1.25 的新特性，在此之前 cargo 如原文默认使用 --lib 。

**Comment by honyxiao** [comment]
了解了。刚学，没用过之前的版本～
顺便问下，其他地方的翻译也是基于某个特定的版本上吗？还是仅仅同步英文版本原文？
ps:看过了第1版，现在在看第2版，感觉比第一版通俗易懂多了，感谢各位大佬的贡献。

**Comment by KaiserY** [comment]
书上说用的 1.21 的 Rust :smile:

**Comment by xiaods** [comment]
看看要不要加注释，表明1.25已经有了。

**Comment by xiaods** [comment]
1.26今天发布，本书英文版本已经随之发布。请关注。
