### ISSUE TITLE
文中的文档连接地址 建议全部改成绝对路径 点击跳转不对 

### ISSUE THREAD

**Issue by wangtxxl** [KaiserY/trpl-zh-cn#2]
比如 ../std/net/enum.IpAddr.html
改成
https://doc.rust-lang.org/std/net/enum.IpAddr.html
大大好厉害 膜拜

**Comment by KaiserY** [comment]
还在施工中，大体翻译完后会修改一下:smile:
欢迎 PR 🎉

**Comment by KaiserY** [comment]
已经修改，有问题请 reopen 或 PR。
