### ISSUE TITLE
Mistake?

### ISSUE THREAD

**Issue by standbyme** [KaiserY/trpl-zh-cn#202]
[Slices](https://github.com/KaiserY/trpl-zh-cn/blob/master/src/ch04-03-slices.md#%E5%AD%97%E7%AC%A6%E4%B8%B2-slice)
![图 4-6](https://github.com/KaiserY/trpl-zh-cn/raw/master/src/img/trpl04-06.svg?sanitize=true)
Where is `capacity` in world?

**Comment by Turing-Chu** [comment]
##### 1. 最好理解C/C++中指针的概念, 以及指针在内存中如何存储的
##### 2. world无需存储容量信息，只需存储数据(此处为字符串)的起始地址和数据的字节长度即可.
##### 3.  原书原图 [trpl04-06.svg](https://github.com/rust-lang/book/blob/master/second-edition/src/img/trpl04-06.svg)

**Comment by standbyme** [comment]
@Turing-Chu 
Get it. Thanks.(My Chinese input method doesn't work....)
