### ISSUE TITLE
FontAwesome 挂掉导致图标不显示

### ISSUE THREAD

**Issue by BLumia** [KaiserY/trpl-zh-cn#239]
不清楚是什么时候开始， https://kaisery.github.io/trpl-zh-cn/ 这里的所有 font-awesome 图标都不显示了，导致页面上方导航按钮不显示，代码块右上角本来应该有的运行按钮不显示。 F12 可以看到浏览器请求了 https://kaisery.github.io/trpl-zh-cn/_FontAwesome/css/font-awesome.css 得到了 404 。

实在不是很熟悉 mdbook ，翻 repo 没找到可能相关的地方，对比 commit history 也没看出来是哪里出的问题...

**Comment by KaiserY** [comment]
这个是 Github Pages 的问题，gh-pages 有 fa 的文件，但是因为是下划线开头默认被忽略了。
参考 https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/

**Comment by KaiserY** [comment]
https://github.com/KaiserY/trpl-zh-cn/commit/4042d694f7df5ff052298e546cb775d527de7955
