### ISSUE TITLE
ch19-01 段落重复

### ISSUE THREAD

**Issue by AlfnXd** [KaiserY/trpl-zh-cn#264]
具体位置在 [使用-extern-函数调用外部代码](https://kaisery.github.io/trpl-zh-cn/ch19-01-unsafe-rust.html#a%E4%BD%BF%E7%94%A8-extern-%E5%87%BD%E6%95%B0%E8%B0%83%E7%94%A8%E5%A4%96%E9%83%A8%E4%BB%A3%E7%A0%81)

![image](https://user-images.githubusercontent.com/8044101/48947225-603dc480-ef6b-11e8-9242-ffc20b1aeea4.png)

红框这一段和上两段重复，且在英文版中没有找到对应段落。

**Comment by KaiserY** [comment]
OK
