### ISSUE TITLE
2018-edition 和 second-edition 目录下的内容被移走了，不能比较着优化翻译了

### ISSUE THREAD

**Issue by xiaohulu** [KaiserY/trpl-zh-cn#267]
忙了一个月，准备回来继续翻译，却发现 second-edition 目录下的文档已经被移走了。

这是 [被移走后的样子](https://github.com/rust-lang/book/blob/master/second-edition/src/ch00-00-introduction.md)

接下来的翻译，怎么办呢？

**Comment by KaiserY** [comment]
第一版、第二版和 2018 版的都被移走了，然后根目录多了一个 `src`。估计是准备合并？

**Comment by KaiserY** [comment]
准备跟进 https://github.com/rust-lang/book/tree/master/src 向 2018 edition 进发 😄

**Comment by xiaohulu** [comment]
你给力，我跟进 😄
