### ISSUE TITLE
有些章节明显是机器人翻译啊，看得我想撞墙

### ISSUE THREAD

**Issue by lidanger** [KaiserY/trpl-zh-cn#300]
有些章节明显是机器人翻译啊，看得我想撞墙。。

**Comment by KaiserY** [comment]
哪些章节？

**Comment by lidanger** [comment]
7，9，10，总之就是越往后越是看不进去，前几天也才看到第10章。
或许只是有些地方用词不太妥，有些地方语句不通顺，有些地方可以意译。

**Comment by ttys3** [comment]
如果你觉得翻译得不好，或者有改进的地方，你可以提PR.
在这里抱怨别人的义务劳动，不太好吧？

**Comment by lidanger** [comment]
这么长时间还没关啊。。
