### ISSUE TITLE
附录B中 T : 'static  的解释翻译错误

### ISSUE THREAD

**Issue by Rmcsy** [KaiserY/trpl-zh-cn#306]
位置：
`appendix-02-operators` / `表 B-5: Trait Bound 约束` / `T : 'static`

原文： `Generic type T contains no borrowed references other than 'static ones`
错误翻译：`泛型 T 包含了除 'static 之外的非借用引用`
正确翻译：`泛型 T 不包含除 'static 之外的借用引用`

**Comment by KaiserY** [comment]
a39a5cebfa8a7f730493da56a611c4d17c6e3e96
