### ISSUE TITLE
附录 G：Rust 是如何开发的与 “Nightly Rust” 中的typo

### ISSUE THREAD

**Issue by Rmcsy** [KaiserY/trpl-zh-cn#307]
位置：`appendix-07-nightly-rust`/`Choo, Choo!（开车啦，逃）发布通道和发布时刻表（Riding the Trains）`

原翻译：所以从 stable 生成 beta 分支后，新版的 beta 分之也再次从 nightly 生成：
更正：所以从 **beta** 生成 **stable** 分支后，新版的 beta **分支**也再次从 nightly 生成：

**Comment by KaiserY** [comment]
a39a5cebfa8a7f730493da56a611c4d17c6e3e96
