### ISSUE TITLE
部分章节标题中"common"翻译成"常见"感觉更合适

### ISSUE THREAD

**Issue by Turing-Chu** [KaiserY/trpl-zh-cn#313]
原标题为"Common Programming Concepts",  此处commen 意指其他语言中也有的。

如下图,
![image](https://user-images.githubusercontent.com/13805470/58750983-59b87880-84cb-11e9-9411-f629ec366791.png)

另 google翻译解释

![image](https://user-images.githubusercontent.com/13805470/58751120-f9c2d180-84cc-11e9-81d4-c989d9b59811.png)

**Comment by KaiserY** [comment]
当时应该是采用了机翻的结果 😂 
https://translate.google.com/#auto/zh-CN/Common%20Programming%20Concepts

**Comment by Turing-Chu** [comment]
嗯，明天我改下吧。
