### ISSUE TITLE
readme里提到的加速站点似乎不再能正常工作了

### ISSUE THREAD

**Issue by ICEYSELF** [KaiserY/trpl-zh-cn#323]
加速站点似乎出现了一些问题，在我这里无法访问。使用chinaz提供的工具进行检查，获得结果如下
![图片](https://user-images.githubusercontent.com/29348140/62768796-3cef8100-baca-11e9-925b-7b53d76d614a.png)
出于个人用途我自行建立了一个镜像，暂时还没有绑定域名，可否考虑添加到readme中？

http://120.78.128.153/rustbook/

**Comment by KaiserY** [comment]
行，你 PR 加上吧。

**Comment by ICEYSELF** [comment]
done
