### ISSUE TITLE
===== 请注意原版有一些新增的内容 ======

### ISSUE THREAD

**Issue by FreeWong** [KaiserY/trpl-zh-cn#325]
在 Dangling References 的内容上面，原书新增了一大段的新内容，请知晓 ！
另外，感谢作者的辛勤工作，为大家翻译这些优秀的书籍。。。

https://github.com/rust-lang/book/blob/master/src/ch04-02-references-and-borrowing.md

**Comment by KaiserY** [comment]
好的
