### ISSUE TITLE
部分章节已与官网不一致

### ISSUE THREAD

**Issue by Rmcsy** [KaiserY/trpl-zh-cn#355]
1.  18.3 `遗留模式： ref 和 ref mut` 部分 已被[移除](https://github.com/rust-lang/book/commit/c81b31d7acda14f50752f3a0103801ce576d0055)
另外该部分有个小错误："比如希望可变地借用结构体的部分值而**可变地**借用另一部分的情况"  应为**不**可变
2. 18.3 `通过 ... 匹配值的范围` 部分语法已经[改变](https://doc.rust-lang.org/stable/book/ch18-03-pattern-syntax.html#matching-ranges-of-values-with-)，由`...`改为`..=`
3. 19.2 `高级生命周期` 整章已被[移除](https://github.com/rust-lang/book/commit/10f89936b02dc366a2d0b34083b97cadda9e0ce4)
4. 是否考虑添加 [title-page.md](https://github.com/rust-lang/book/blob/master/src/title-page.md)?
5. [ch20-04-storing-threads.md](https://github.com/KaiserY/trpl-zh-cn/blob/master/src/ch20-04-storing-threads.md) 和 [ch20-05-sending-requests-via-channels.md](https://github.com/KaiserY/trpl-zh-cn/blob/master/src/ch20-05-sending-requests-via-channels.md) 两文件可以被清理

**Comment by KaiserY** [comment]
好的，最近更新一下 😄

**Comment by ICEYSELF** [comment]
will give it a try today

**Comment by ICEYSELF** [comment]
我们应该close这个PR，还是留着它，直到我们完成对内容的更新？

**Comment by KaiserY** [comment]
先保持 open 吧，最近集中更新下。

PS: 其它问题也欢迎反馈 :smile:

**Comment by KaiserY** [comment]
已经简单过了一遍，有问题请开 issue 或 PR :satisfied:
