### ISSUE TITLE
第二章翻译错误

### ISSUE THREAD

**Issue by NewLanded** [KaiserY/trpl-zh-cn#388]
你好, 第二章有一句翻译为  "现在调用 io 的关联函数 stdin", 原文是 "Now we’ll call the stdin function from the io module". 这里的stdin应该不是io的关联函数吧, 只是一个普通函数.

**Comment by ICEYSELF** [comment]
stdin确实应该是一个普通函数，原文里也没有指出它是关联函数

> Recall that we included the input/output functionality from the standard library with use std::io; on the first line of the program. Now we’ll call the stdin function from the io module:
> ```
> ...
> ```
> If we hadn’t put the use std::io line at the beginning of the program, we could have written this function call as std::io::stdin. The stdin function returns an instance of std::io::Stdin, which is a type that represents a handle to the standard input for your terminal.
