### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by lsgxeva** [KaiserY/trpl-zh-cn#39]
原文URL地址: https://doc.rust-lang.org/nightly/book/second-edition/ch02-00-guessing-game-tutorial.html#handling-invalid-input
原文内容: Switching from an expect call to a match expression is how you generally move from crash on error to actually handling the error. 

翻译版URL地址: https://kaisery.github.io/trpl-zh-cn/ch02-00-guessing-game-tutorial.html
翻译内容: 从expect调用切换到expect语句是如何从遇到错误就崩溃到真正处理错误的常用手段。

应该翻译为: 从expect调用切换到match语句是如何从遇到错误就崩溃到真正处理错误的常用手段。

**Comment by KaiserY** [comment]
OK
