### ISSUE TITLE
Trait 建议翻译为 特质

### ISSUE THREAD

**Issue by murphil** [KaiserY/trpl-zh-cn#43]
个人理解，Rust的设计思想是，Trait组合胜于模板继承（类继承），也就是常说的组合胜于继承，因此只有Trait而没有Class。如果需要提到这一概念，使用“特质组合”比“特征组合”（Rust社区似乎倾向于 特征 这个翻译）要更顺口。 而且 Trait 中可以包含默认实现， “特质”听起来像是有重量的东西，而“特征”、“特性”则更像没有质量的抽象概念。

**Comment by KaiserY** [comment]
上一版翻译成“特性”来着，当时的社区反映是这类 Rust 特有的东西尽量不翻译，同理还有 slice（这个之前翻译为切片，据说跟 C++ 还是啥的有冲突）。

**Comment by murphil** [comment]
;D 然而 Trait 并不是 Rust 特有的东西，并且 Scala 里面翻译为特质。
冲突也不是什么问题，即便没有 Rust，其它语言间也必然会有冲突。。。如果没有，Rust 来凑。。。我的意思是说，没有必要为了照顾其它语言用户的感受而谨小慎微，更何况还是“其它语言相关资料的翻译作品”的用户。  
确实有一些翻译，像 Function 翻译为“函数”，是很不靠谱的，但那是历史遗留问题，并已被广泛接受。以至于，起码在编程领域，提到“函数”，你既不会想到“函”，也不会想到“数”，它已经成为了一个既不表音，也不表义的异化存在(在清朝它应该还是能够表义的)。
类似的，如果我们把 Trait 翻译成 ”函质“，就一样的不靠谱。然而我们并不准备这样做

**Comment by KaiserY** [comment]
考察一番之后，我想起来了，之前不建议翻译 trait 却有道理，并不是说 trait 这个单词为 Rust 所特有，而是说 Rust 的 trait 是没有开销的，它可以静态分发，而其他语言中的 trait 或者 interface 基本都是运行时多态的一种。

**Comment by KaiserY** [comment]
不过，从概念来说确实没有影响，解释上加以区别的话，这么翻译应该可行。

**Comment by murphil** [comment]
静态分发有空间上的开销，在C++中似乎还是挺严重的问题。默认类型擦除和动态分发的似乎只有Java系，它们可以使用接口来作为类型约束，其它派别中好像默认是不可以的。
即便Rust真的和其它语言完全不一样，我也完全无法想象，像Trait这么一个单词里竟然有着如此复杂的含义。
譬如Rust中的函数有生存期参数，这才是真的和其它大部分语言不同，那么函数这个词是不是应该保留原文?

**Comment by murphil** [comment]
如果需要特别解释的话。。。实际上 trpl 原版我感觉写得真不怎么样，修订过程中发现一些费解的地方，看原文发现确实就是那么表达的，以至于必须在表述上做一些修改，才能清晰的表达出作者们可能想要表达的意图。 而且还一惊一乍的，把读者当成幼儿园的小朋友么? 有太多的地方我觉得需要加上注释，然而最终并没有加

**Comment by heibor** [comment]
站在编程文档的角度，我觉得不翻译也许更好，一个中国化的名词的确不好提炼，而且放在文章中用中文读读出来总感觉怪里怪气的，没有一脉相承的顺畅感。

**Comment by huangjj27** [comment]
@murphil 

>  trpl 原版我感觉写得真不怎么样，修订过程中发现一些费解的地方

这可能是因为rust语言目前的学习曲线还是很陡峭, 所以不太容易理解.

> 看原文发现确实就是那么表达的，以至于必须在表述上做一些修改，才能清晰的表达出作者们可能想要表达的意图

每种语言在对事物建模的方式上都有差异, 需要修改表述也是合理的.

> 有太多的地方我觉得需要加上注释，然而最终并没有加

你可以将你的想法在英文原文仓库上提出issue, 或者PR, 会有工作人员处理的.

**Comment by W4anD0eR96** [comment]
@huangjj27 trait 翻译成特性应当是比较恰当的, 在 scala 或 Perl 6 中也常出现这个词, 一般来说就是用**特性**来翻译

**Comment by wizardforcel** [comment]
然而 PHP 里面通常叫做“性状”，你们也可以借鉴。

**Comment by W4anD0eR96** [comment]
@wizardforcel 个人感觉`性状`过于学术化, 不适合`rust`的推广. 当然怎么最后确定对应翻译也是讨论的结果.

**Comment by huangjj27** [comment]
实际上, 对于大中华地区各部分可能会对同一个术语有不同翻译, 会增加一定的学习成本, 因此建议对`trait`以及其他专有术语不进行翻译.

**Comment by W4anD0eR96** [comment]
@huangjj27 赞同,  不翻译`trait`为好.

@KaiserY 可以考虑close这个issue.

**Comment by shiny** [comment]
> 然而 PHP 里面通常叫做“性状”，你们也可以借鉴。

PHP 中文手册里的 Trait 章节是我翻译的，没有翻译成 “性状”。当时也被 trait 怎么翻译难倒了，请教了 PHP 开发核心成员 Laruence，他的建议是保留原文不翻译。
