### ISSUE TITLE
Rust 水群群号是错的？

### ISSUE THREAD

**Issue by iamwhcn** [KaiserY/trpl-zh-cn#495]
Rust 水群：253849562

这个群号搜不到啊

**Comment by ICEYSELF** [comment]
这个水裙在疫情时代的时候因为众所周知的原因爆炸了，我们建了新的（不过现在满了）

738709774

**Comment by Why-Not-GitHub** [comment]
@ICEYSELF 麻烦群主退一下群，让我进群:rofl:
