### ISSUE TITLE
考虑添加一个GitHub Action以自动构建更新

### ISSUE THREAD

**Issue by iamwhcn** [KaiserY/trpl-zh-cn#511]
添加一个GitHub Action以在每次修改后自动构建并发布，这样很方便的保持网页实时更新。

**Comment by iamwhcn** [comment]
尤其是深圳站点，好像更新不是很同步

**Comment by ICEYSELF** [comment]
深圳站点是我手动更新的，接下来我考虑写个脚本自动化一下这个流程

**Comment by KaiserY** [comment]
gh-pages 的 github actions 已经添加。

**Comment by KaiserY** [comment]
其他 actions 欢迎 issue 或者 pr，此 issue 先关闭。
