### ISSUE TITLE
18 模式用来匹配值的结构

### ISSUE THREAD

**Issue by node** [KaiserY/trpl-zh-cn#519]
18章的目前这个标题初看有点儿懵，建议是否可以再优化和打磨一下。

按照个人粗浅理解，原文“Patterns and Matching” 可能是想重点体现下 Rust 里面的模式概念，以及值匹配的设计理念和应用场景。

另外“6. Enums and Pattern Matching”虽也有提到，只是仅限于非常浅的介绍。

**Comment by KaiserY** [comment]
我记得以前的标题很长来着，我改下。
