### ISSUE TITLE
建议 traits 翻译成“禀性”，“天赋异禀”的“禀”，简称“禀”。

### ISSUE THREAD

**Issue by Jiuyong** [KaiserY/trpl-zh-cn#534]
国人学英语太多，学文言文太少。

**Comment by AFGXF** [comment]
[《中国人失掉自信力了吗》](https://baike.baidu.com/item/%E4%B8%AD%E5%9B%BD%E4%BA%BA%E5%A4%B1%E6%8E%89%E8%87%AA%E4%BF%A1%E5%8A%9B%E4%BA%86%E5%90%97/947682#1)

**Comment by Jiuyong** [comment]
张汉东大佬已经定下来决定翻译成“特性”了，虽然对于我这样的完美主义者不算满意，但是基于现实情况也可以接受。
