### ISSUE TITLE
17-02中Trait对象的对象安全规则翻译有误

### ISSUE THREAD

**Issue by dai-pch** [KaiserY/trpl-zh-cn#54]
关于对象安全的规则第一条，原文为
“The trait does not require Self to be Sized”
应译为
“该 trait 不能要求 Self 是 Sized”
而非现有译文中的
“该 trait 要求 Self 不是 Sized”
我看的时候纠结了半天。

另外，17-02还有不少地方很难懂，看了原文才知道是什么意思。建议改进一下。

**Comment by KaiserY** [comment]
OK

**Comment by huangjj27** [comment]
已经修正了该翻译
