### ISSUE TITLE
ch19-02中的lifetime bound

### ISSUE THREAD

**Issue by heibor** [KaiserY/trpl-zh-cn#60]
感觉ch19-02中的lifetime bound可译为生命周期绑定，从译文可以很容易理解是把一个类型的生命期绑定到至少和另一个类型的生命周期一样长.

**Comment by KaiserY** [comment]
嗯，这个可以有，确实没有歧义。

**Comment by huangjj27** [comment]
如果一定需要翻译, 我认为可以翻译为`生命周期约束`, 意义为一个变量的生命周期需要满足约束, 其所在程序才是合法以及安全的.
其他可选方案为不进行该名词的翻译.
