### ISSUE TITLE
4.1节中的翻译错误

### ISSUE THREAD

**Issue by tomial** [KaiserY/trpl-zh-cn#625]
4.1[只在栈上的数据：拷贝](https://kaisery.github.io/trpl-zh-cn/ch04-01-what-is-ownership.html#%E5%8F%AA%E5%9C%A8%E6%A0%88%E4%B8%8A%E7%9A%84%E6%95%B0%E6%8D%AE%E6%8B%B7%E8%B4%9D)小节结尾处：

> 任何不需要分配内存或某种形式资源的类型都可以实现 Copy 。

原文为：
> and nothing that requires allocation or is some form of resource can implement Copy

而allocation的定义是：
> 原文：This process is called _allocating on the heap_ and is sometimes abbreviated as just _allocating_ (pushing values onto the stack is not considered allocating).
> 翻译：这个过程称作 在堆上分配内存（allocating on the heap），有时简称为 “分配”（allocating）。

【不需要分配内存】容易造成困扰，这里应该改为
> 任何不需要在堆上分配内存或某种形式资源的类型都可以实现 Copy

**Comment by Sefank** [comment]
我感觉既然前面已经提到了 “分配”（allocating）这个词在不额外说明的情况下是指“在堆上分配”，那么出于尊重原文的考虑，这里应该就不需要额外强调。原文这样省略也有其合理之处：一方面，Rust 的语言设计有意弱化栈空间和堆空间的概念；另一方面，确实大部分情况下提到“分配”内存空间都是是指“在堆上分配”。

**Comment by tomial** [comment]
> 

回头看了下发现文中有特别指出
> 将数据推入栈中并不被认为是分配

那省略掉确实没有问题
