### ISSUE TITLE
13.1节与英文版不一致

### ISSUE THREAD

**Issue by Narukara** [KaiserY/trpl-zh-cn#673]
13.1节（闭包）的内容和英文版看上去非常不一样，请问是正在翻译中吗？后面的几节似乎也有一些出入

**Comment by KaiserY** [comment]
有一阵子没更新了，最近我检查一遍。

**Comment by TeCHiScy** [comment]
> 有一阵子没更新了，最近我检查一遍。

开始检查了么，或者我也来参与这一章校对

**Comment by biaji** [comment]
因原英文在去年更新了example。导致目前中文和英文示例对不上。对应提交：

[https://github.com/rust-lang/book/commit/ce4da5ccbfc13105b444e8528a3603157773ffa7](https://github.com/rust-lang/book/commit/ce4da5ccbfc13105b444e8528a3603157773ffa7)
