### ISSUE TITLE
20230116 更新后 排版出现错位问题 

### ISSUE THREAD

**Issue by ancion** [KaiserY/trpl-zh-cn#677]
昨天我刚好看到第十章，生命周期那边. 今天打开一看，怎么和昨天看到的不一样，文不对意， 我还以为是我记错了，然后运行代码的结果也不对，上下看了一遍后，发现代码块的位置都偏移了。 

略举一例 ： 这里原本是有一个代码块的 
![image](https://user-images.githubusercontent.com/49437191/212803734-0148d0df-9ebc-49e8-8df8-001427ad54b0.png)

然后上下找了一遍， 出现在示例 10-24 的位置，
![image](https://user-images.githubusercontent.com/49437191/212803911-cee00c0a-85c2-4629-8038-15c595713b0b.png)

其他的位置我没看，不清楚有没有类似问题

**Comment by KaiserY** [comment]
最近在更新，没拉分支:joy:，你要不 checkout 下前几天的 commit 看下哈

**Comment by KaiserY** [comment]
我尽快修复下第十章
