### ISSUE TITLE
PDF的“确”字使用的是日文字体。

### ISSUE THREAD

**Issue by cathay4t** [KaiserY/trpl-zh-cn#74]
PDF 25页
```
Cargo 有一个机制来确保任何人在任何时候重新构建代码
```

这里的"确"字是日文字体。
详见：
https://www.google.com/search?q=%E7%A1%AE+%E6%97%A5%E6%96%87&ie=utf-8&oe=utf-8&client=firefox-b-ab

http://www.zdic.net/z/1f/js/786E.htm

**Comment by KaiserY** [comment]
Markdown 里确实是中文，估计是 GitBook 的问题。
[https://github.com/KaiserY/trpl-zh-cn/blob/master/src/ch02-00-guessing-game-tutorial.md](https://github.com/KaiserY/trpl-zh-cn/blob/master/src/ch02-00-guessing-game-tutorial.md)

**Comment by cathay4t** [comment]
Closing. It's a gitbook bug and I failed to find a good way to report bug to them.

**Comment by cathay4t** [comment]
Sent a bug report via https://www.gitbook.com/contact
