### ISSUE TITLE
疑似错误

### ISSUE THREAD

**Issue by green961** [KaiserY/trpl-zh-cn#766]
https://kaisery.github.io/trpl-zh-cn/ch07-04-bringing-paths-into-scope-with-the-use-keyword.html

```rust
mod front_of_house {
    pub mod hosting {
        pub fn add_to_waitlist() {}
    }
}

use crate::front_of_house::hosting;

mod customer {
    pub fn eat_at_restaurant() {
        hosting::add_to_waitlist();
    }
}
```

注意这里还有一个警告说 use 在其作用域内不再被使用！为了修复这个问题，可以将 use 移动到 customer 模块内，或者在子模块 customer 内通过 `super::hosting` 引用父模块中的这个短路径。

`super::hosting` 应该是 `super::front_of_house::hosting`

![搜狗截图20240208221610](https://github.com/KaiserY/trpl-zh-cn/assets/81228933/9d0f9de5-09b3-48c6-8a68-cbbe3b942177)

![搜狗截图20240208223211](https://github.com/KaiserY/trpl-zh-cn/assets/81228933/a246f317-1343-42ba-a9cf-031f7b9fb284)

**Comment by woc777** [comment]
并没有问题。你可能理解错误了, 原文的意思是把代码改成这样:
```
use crate::front_of_house::hosting;

mod customer {
    super::hosting;
    pub fn eat_at_restaurant() {
        hosting::add_to_waitlist();
    }
}
```

**Comment by green961** [comment]
```rust
// 嗯是的, 改用`super`的时候, 下面这句要保留
use crate::front_of_house::hosting;

mod customer {
  use super::hosting;
  pub fn eat_at_restaurant() {
    hosting::add_to_waitlist();
  }
}

mod customec {
  pub fn eat_at_restaurant() {
    super::hosting::add_to_waitlist();
  }
}

```
