### ISSUE TITLE
无法预览构建好的文档

### ISSUE THREAD

**Issue by pk49800** [KaiserY/trpl-zh-cn#775]
按照README构建好文档后，使用simple-http-server预览文档出现如下错误：
![截屏2024-03-01 18 33 57](https://github.com/KaiserY/trpl-zh-cn/assets/36910388/faf0c502-5af0-40b3-ab97-0bd772c8253f)

**Comment by epiloguess** [comment]
尝试
`simple-http-server .\book -i`

**Comment by KaiserY** [comment]
试下
```
simple-http-server ./book/html/ -i
```
README 里的应该是 Windows 的路径

**Comment by pk49800** [comment]
> 试下
> 
> ```
> simple-http-server ./book/html/ -i
> ```
> 
> README 里的应该是 Windows 的路径

`simple-http-server ./book -i` 可以，请问下这个程序和`mdbook serve`命令的效果有什么不同？

**Comment by KaiserY** [comment]
试了下感觉没啥区别，这就是个 http-server，这块内容是 merge 进来的，方便简单部署。
