### ISSUE TITLE
关于贡献，我是否该提交我认为更合适的翻译

### ISSUE THREAD

**Issue by llianc62** [KaiserY/trpl-zh-cn#809]
首先非常感谢所有贡献者目前做出的所有工作和的翻译结果，能够让我们能方便的学习Rust，为国内学习Rust做出的贡献！

首先说一下我全书读起来一些翻译的感受：

1. 有点像机器翻译，或者说不够native，还是英语的表达形式。
2. 一些原句子过长，原样翻译会导致句子主谓宾结构过于臃长，阅读理解苦难，应该尽量让句子短些、清晰些。 cut sentence shorter!

绝大部分都不影响阅读和理解，我已经读到了第13章；当我在读闭包的内容时，感觉理解起来非常吃力，我也怀疑当天的精神不是特别好（前一天没有睡好），以下是我感觉影响理解的部分：

> 一旦闭包捕获了定义它的环境中一个值的引用或者所有权（也就影响了什么会被移 _进_ 闭包，如有)，闭包体中的代码定义了稍后在闭包计算时对引用或值如何操作（也就影响了什么会被移 _出_ 闭包，如有）。闭包体可以做以下任何事：将一个捕获的值移出闭包，修改捕获的值，既不移动也不修改值，或者一开始就不从环境中捕获值。
> 
> 闭包捕获和处理环境中的值的方式影响闭包实现的 trait。Trait 是函数和结构体指定它们能用的闭包的类型的方式。取决于闭包体如何处理值，闭包自动、渐进地实现一个、两个或三个 `Fn` trait。
> 
> 1. `FnOnce` 适用于能被调用一次的闭包，所有闭包都至少实现了这个 trait，因为所有闭包都能被调用。一个会将捕获的值移入闭包体的闭包只实现 `FnOnce` trait，这是因为它只能被调用一次。
> 2. `FnMut` 适用于不会将捕获的值移入闭包体的闭包，但它可能会修改被捕获的值。这类闭包可以被调用多次。
> 3. `Fn` 适用于既不将被捕获的值移入闭包体也不修改被捕获的值的闭包，当然也包括不从环境中捕获值的闭包。这类闭包可以被调用多次而不改变它们的环境，这在会多次并发调用闭包的场景中十分重要。

## 第一部分，关于闭包捕获值的描述：

原文： 

> Once a closure has captured a reference or captured ownership of a value from the environment where the closure is defined (thus affecting what, if anything, is moved into the closure), the code in the body of the closure defines what happens to the references or values when the closure is evaluated later (thus affecting what, if anything, is moved out of the closure). A closure body can do any of the following: move a captured value out of the closure, mutate the captured value, neither move nor mutate the value, or capture nothing from the environment to begin with.

就像这样，这些句子的表达式，就是 _you can do some thing or do nothing._
比较日常的句子使用这种形式我觉得都还好理解，他这里的原文就是这种形式，我感觉可能作者在表述的时候没有过多去考虑读者阅读和学习的感受，或者文化的差异； 我觉得在了解一个定义或者一个概率的时候，一定要有正确的表述顺序，不然理解起来很难受，最起码在中文中是这样的感受！

我尝试翻译：

一旦一个闭包从定义闭包的环境中捕获了一个引用或捕获了一个值的所有权（从而影响到将内容 _移入_ 闭包，如有）， 在定义闭包的代码主体中，对闭包捕获的值在后续闭包体计算时发生什么变化（从而影响将内容被 _移出_ 闭包，如有）。闭包体可以做以下事情： 捕获值移入闭包，修改捕获的值，既不移动也不修改值，将捕获的值移出闭包，或者不从环境中捕获值。

## 第二部分，关于三种 trait 的说明：

原文：

> 1. `FnOnce` applies to closures that can be called once. All closures implement at least this trait, because all closures can be called. A closure that moves captured values out of its body will only implement `FnOnce` and none of the other `Fn` traits, because it can only be called once.
> 2. `FnMut` applies to closures that don’t move captured values out of their body, but that might mutate the captured values. These closures can be called more than once.
> 3. `Fn` applies to closures that don’t move captured values out of their body and that don’t mutate captured values, as well as closures that capture nothing from their environment. These closures can be called more than once without mutating their environment, which is important in cases such as calling a closure multiple times concurrently.

我的翻译：

1. `FnOnce` 适用于只能被调用一次的闭包，所有闭包都至少实现了这个 trait，因为所有闭包都能被调用。将捕获的值移入闭包体的闭包只能实现 `FnOnce` trait，不能实现 `Fn` trait , 因为它只能被调用一次。
2. `FnMut` 适用于不将捕获的值移入且没有移出的闭包体，但是它可以修改捕获的值。这类闭包可以被调用多次。
3. `Fn` 适用于既不将被捕获的值移入闭包体也不修改被捕获的值的闭包，当然也包括不从环境中捕获值的闭包。这类闭包可以被调用多次而不改变它们的环境，这在会多次并发调用闭包的场景中十分重要。

没有参与过翻译工作，可能有些问题，希望有专业的规范或者贡献手册，这样我可以做一些小的贡献，如果可以的话。

**Comment by yancy-hong** [comment]
我也是初学者，有些语句确实有点不好理解

**Comment by KaiserY** [comment]
我最近看下，有问题欢迎 PR 😄

**Comment by yancy-hong** [comment]
这是来自QQ邮箱的上学自动回复邮件。你好，我最近正在读书中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by llianc62** [comment]
关于闭包在阅读时没有理解的我在chatGPT找到了比较好的解释，希望可以帮助同样对闭包定义有疑惑的朋友：

在Rust中，闭包是可以捕获环境变量的匿名函数，Rust为闭包定义了三个不同的trait：`FnOnce`、`FnMut`和`Fn`。它们之间的区别主要在于闭包如何捕获和使用环境中的变量。

### 1. `FnOnce` Trait

`FnOnce`是最基本的闭包trait，表示闭包只能被调用一次。它之所以叫`FnOnce`，是因为它捕获环境变量的方式可能会将这些变量的所有权移动到闭包内部，因此闭包只能消费这些变量一次。

- **捕获方式**：按值捕获（move）。
    
- **适用场景**：适用于需要消费所有权或执行只能一次的操作。
    
- **示例**：
    
```rust
let x = String::from("hello");
let consume_x = move || {
    println!("{}", x);
};
consume_x(); // 闭包调用一次后 x 被消耗
// consume_x(); // 再次调用将导致编译错误，因为x的所有权已经被消耗
```
    

### 2. `FnMut` Trait

`FnMut`表示闭包可以被多次调用，但在调用过程中可能会修改它捕获的环境变量。闭包可以通过可变引用捕获环境中的变量，因此它能够修改这些变量。

- **捕获方式**：按可变引用捕获（&mut）。
    
- **适用场景**：适用于需要多次调用且每次调用可能会改变环境状态的情况。
    
- **示例**：
    
```rust
let mut x = 0;
let mut increment_x = || {
    x += 1;
};
increment_x();
increment_x();
println!("{}", x); // 输出 2
```

### 3. `Fn` Trait

`Fn`是最强的trait，表示闭包可以被多次调用，而且在调用过程中不会修改或消耗它捕获的环境变量。闭包通过不可变引用捕获变量。

- **捕获方式**：按不可变引用捕获（&）。
    
- **适用场景**：适用于不改变环境状态并且可以安全地多次调用的情况。
    
- **示例**：
    
```rust
let x = 5;
let print_x = || {
    println!("{}", x);
};
print_x(); // 可以多次调用
print_x();
```

### 总结

- **`FnOnce`**：只能调用一次，按值捕获，可能移动所有权。
- **`FnMut`**：可以多次调用，按可变引用捕获，可能修改环境。
- **`Fn`**：可以多次调用，按不可变引用捕获，不会修改环境。

这些trait是互为继承关系的：`FnOnce`是最通用的，`FnMut`继承了`FnOnce`，而`Fn`则继承了`FnMut`。这意味着一个实现了`Fn`的闭包也实现了`FnMut`和`FnOnce`，但反之不成立。


### `Move In` 和 `Move Out` 的定义

在Rust中，**move in** 和 **move out** 是与所有权转移相关的概念，特别是在闭包和函数调用的上下文中。

#### 1. **Move In**

**Move in** 指的是将一个变量的所有权从它的原始作用域中转移到另一个上下文中，例如一个闭包或函数中。当一个变量被 move in 时，它的所有权被移动到新的上下文，而原始作用域将不再拥有对该变量的访问权。

- **典型场景**：在Rust中，当你使用 `move` 关键字或当闭包自动按值捕获变量时，变量的所有权就会被移动到闭包中。移动后，原始作用域中的变量不再有效，你无法再次使用它。

**示例**：

```rust
let s = String::from("hello");

let closure = move || {
    println!("{}", s); // s 被 move 到闭包中
};

// s 在这里已经不能再使用
```

在这个例子中，字符串 `s` 的所有权被移动到闭包 `closure` 中，因此在 `closure` 之外不能再使用 `s`。

#### 2. **Move Out**

**Move out** 指的是将一个变量的所有权从当前上下文（如闭包或函数）转移到另一个上下文（例如另一个变量或函数）中。当闭包被调用或返回时，捕获的变量可以被移出闭包，这就是“move out”的过程。

- **典型场景**：闭包执行完毕后，如果它捕获的变量的所有权被转移出闭包（例如通过返回值或将闭包传递给另一个函数），这就是 move out 的过程。

**示例**：

```rust
let s = String::from("hello");

let closure = move || {
    s // s 被 move 到闭包，并在闭包返回时 move 出闭包
};

let s2 = closure(); // s 的所有权被转移给 s2
```

在这个例子中，`s` 被移入闭包，在闭包被调用后，`s` 的所有权又被移出闭包并赋值给变量 `s2`。

### 总结

- **Move In**：将变量的所有权从原始作用域移到新的上下文（如闭包或函数），导致原始作用域不再拥有该变量的所有权。
- **Move Out**：将变量的所有权从当前上下文（如闭包或函数）移到另一个上下文，通常是闭包返回值的场景。

这些概念是Rust所有权模型的核心部分，确保在不同上下文中对变量的使用是安全且明确的。
