### ISSUE TITLE
“列表 10-20” 建议翻译为“码签 10-20”

### ISSUE THREAD

**Issue by Houcer** [KaiserY/trpl-zh-cn#83]
文章里用来指代对应代码块的称呼，类似论文里“图 3-1”之类的。歪果仁说 "list 10-1"，"list"应该更类似于“便签条”，“收据单”的意思吧。“列表”这个称呼总让我出戏，其实本来打算建议“码单”来着，不过好像更出戏，额

**Comment by KaiserY** [comment]
不如直接叫 "示例" 得了:joy:

**Comment by Houcer** [comment]
哈，也是，绕的有点晕

**Comment by huangjj27** [comment]
附议使用示例

**Comment by huangjj27** [comment]
修改已经在https://github.com/KaiserY/trpl-zh-cn/commit/57a1a0b98a3c9a1efc995b1c34562d8398b68e71 中进行更改, 该issue可以关闭.
