### ISSUE TITLE
lifetime 的翻译讨论

### ISSUE THREAD

**Issue by cuyl** [KaiserY/trpl-zh-cn#86]
”生命周期”一般指的是 lifecycle
把 lifetime 也翻译为生命周期是否有歧义？

**Comment by huangjj27** [comment]
`lifecycle`与`lifetime`均是指变量在程序范围中生存了多久, 并没有歧义.
参考自[Object_lifetime-wikipedia](https://en.wikipedia.org/wiki/Object_lifetime):

> In object-oriented programming (OOP), the **object lifetime** (or **life cycle**) of an object is the time between an object's creation and its destruction.
> 
> 在面向对象编程中, 一个对象的**对象生命时(object lifetime)**(或**生命周期(life cycle)**)是该对象产生指销毁的时间区间.

**Comment by KaiserY** [comment]
**生命周期** 这个翻译社区比较认可，第一版讨论相关术语时也没有对此存在多少异议。总之，现在再改个中歧义可能会更大:smile:

**Comment by cuyl** [comment]
原来如此
