### ISSUE TITLE
需求: 集成Travis-CI

### ISSUE THREAD

**Issue by huangjj27** [KaiserY/trpl-zh-cn#89]
留意到issues中有些源码中已经修复, 但是gitbooks.io仍然没有进行更新, 因此提出该需求, 以节约贡献者们的时间.

**Comment by KaiserY** [comment]
Gitbooks 上应该是及时的，如果不及时可能是对方系统的问题，GIthub Pages 上的我整整:smile:

**Comment by huangjj27** [comment]
并不即时0. 0参考 https://github.com/KaiserY/trpl-zh-cn/issues/77#issuecomment-332703509 https://github.com/KaiserY/trpl-zh-cn/issues/83#issuecomment-334985819

**Comment by KaiserY** [comment]
已集成 Travis-CI，有问题欢迎 reopen
