### ISSUE TITLE
重复

### ISSUE THREAD

**Issue by AurevoirXavier** [KaiserY/trpl-zh-cn#91]
Link: [https://kaisery.github.io/trpl-zh-cn/ch15-05-interior-mutability.html#refcellt拥有内部可变性](url)

括号内应该为 Halting Problem

重复出现两次 停机问题

另外 Halting Problem 可以 link 一下 [https://brilliant.org/wiki/halting-problem/]()

**Comment by W4anD0eR96** [comment]
修改已提交为  #128

关于添加链接, 个人感觉这部分以英文文档为准, 翻译还是主要翻译内容, 不要修改原来的结构
